package com.example.util

object LocalizationHelper {

    private val translations = mapOf(
        "en" to mapOf(
            "sportsbook" to "Sportsbook",
            "my_slips" to "My Slips",
            "secure_bank" to "Secure Bank",
            "admin_panel" to "Admin Panel",
            "support" to "Support",
            "balance" to "BALANCE",
            "deposit" to "DEPOSIT",
            "active_bets" to "ACTIVE BETS",
            "ssl_encrypted" to "SSL ENCRYPTED",
            "today_matches" to "Today's Live Sportsbook",
            "all_sports" to "All Sports",
            "football" to "Football",
            "basketball" to "Basketball",
            "tennis" to "Tennis",
            "place_single_bet" to "Place Single Bet",
            "enter_stake" to "STAKE VALUE (ETB)",
            "potential_return" to "POTENTIAL RETURN",
            "safety_score" to "AI Safety Score",
            "prediction_title" to "AI Match Prediction",
            "risk_warning" to "RESPONSIBLE GAMING WARNING",
            "support_chat" to "ShebaOdds Live Rules Desk",
            "chat_placeholder" to "Type your inquiry (English, Amharic, Tigrinya)...",
            "admin_control" to "ShebaOdds Real-Time Admin Panel",
            "user_database" to "Hardware Auditing Database",
            "quick_stats" to "Ledger Analytics Quick Stats",
            "total_odds_line" to "Total Odds Line",
            "gross_estimation" to "Gross Estimation Return",
            "combined_odds" to "Combined Total Odds",
            "total_risk_stake" to "Total Risk Stake",
            "gross_returns" to "Gross Potential Returns",
            "multi_bet_slip" to "Multi-Leg Parlay Slip",
            "clear_all" to "Clear All",
            "ethiopian_calendar" to "Ethiopian Calendar",
            "select_language" to "Select Language",
            "app_name" to "ShebaOdds",
            "app_tagline" to "Smart Bets. Real Wins.",
            "app_welcome" to "Welcome",
            "app_loading" to "Loading...",
            "nav_home" to "Home",
            "nav_football" to "Football",
            "nav_live" to "Live Betting",
            "nav_casino" to "Casino",
            "nav_promotions" to "Promotions",
            "nav_profile" to "Profile",
            "nav_wallet" to "Wallet",
            "nav_history" to "History",
            "nav_tax" to "Tax Center",
            "nav_support" to "Support",
            "nav_settings" to "Settings",
            "auth_login" to "Login",
            "auth_register" to "Register",
            "auth_email" to "Email",
            "auth_password" to "Password",
            "auth_confirm_password" to "Confirm Password",
            "auth_username" to "Username",
            "auth_phone" to "Phone Number",
            "auth_fullname" to "Full Name",
            "auth_forgot_password" to "Forgot Password",
            "auth_reset_password" to "Reset Password",
            "auth_remember_me" to "Remember Me",
            "auth_login_biometric" to "Login with Biometric",
            "auth_use_face_id" to "Use Face ID",
            "auth_use_fingerprint" to "Use Fingerprint",
            "auth_pwd_requirements" to "Password must be at least 8 characters, one uppercase, one lowercase, one number and one special character",
            "wallet_balance" to "Balance",
            "wallet_bonus_balance" to "Bonus Balance",
            "wallet_deposit" to "Deposit",
            "wallet_withdraw" to "Withdraw",
            "wallet_transactions" to "Transactions",
            "wallet_deposit_success" to "Deposit successful!",
            "wallet_withdraw_success" to "Withdrawal successful!",
            "bets_place_bet" to "Place Bet",
            "bets_home_win" to "Home Win",
            "bets_away_win" to "Away Win",
            "bets_draw" to "Draw",
            "bets_over" to "Over",
            "bets_under" to "Under",
            "bets_potential_win" to "Potential Win",
            "bets_stake" to "Stake",
            "bets_odds" to "Odds",
            "bets_accumulator" to "Accumulator",
            "bets_cashout" to "Cash Out",
            "bets_cashout_value" to "Cash Out Value",
            "bets_placed" to "Bet placed!",
            "tax_title" to "Tax Center",
            "tax_rate" to "Tax Rate",
            "tax_rate_value" to "15%",
            "tax_free_limit" to "Tax Free Limit",
            "tax_free_limit_value" to "100 ETB",
            "tax_total_paid" to "Total Tax Paid",
            "tax_total_winnings" to "Total Winnings Taxed",
            "tax_certificate" to "Tax Certificate",
            "tax_monthly_report" to "Monthly Report",
            "matches_live" to "Live",
            "matches_upcoming" to "Upcoming",
            "matches_finished" to "Finished",
            "matches_halftime" to "Halftime",
            "matches_fulltime" to "Fulltime",
            "matches_minute" to "Minute",
            "matches_league" to "League",
            "matches_stats" to "Statistics",
            "matches_events" to "Events",
            "time_today" to "Today",
            "time_tomorrow" to "Tomorrow",
            "time_yesterday" to "Yesterday",
            "time_now" to "Now",
            "time_minutes_ago" to "minutes ago",
            "time_hours_ago" to "hours ago",
            "time_days_ago" to "days ago",
            "time_am" to "AM",
            "time_pm" to "PM",
            "err_required" to "This field is required",
            "err_invalid_email" to "Please enter a valid email",
            "err_pwd_too_short" to "Password must be at least 8 characters",
            "err_pwd_no_upper" to "Password must contain at least one uppercase letter",
            "err_pwd_no_lower" to "Password must contain at least one lowercase letter",
            "err_pwd_no_num" to "Password must contain at least one number",
            "err_pwd_no_special" to "Password must contain at least one special character",
            "err_pwd_no_match" to "Passwords do not match",
            "err_insufficient_bal" to "Insufficient balance",
            "err_invalid_amount" to "Invalid amount",
            "err_network" to "Network error",
            "btn_submit" to "Submit",
            "btn_cancel" to "Cancel",
            "btn_confirm" to "Confirm",
            "btn_back" to "Back",
            "btn_next" to "Next",
            "btn_save" to "Save",
            "btn_edit" to "Edit",
            "btn_delete" to "Delete",
            "btn_close" to "Close"
        ),
        "am" to mapOf(
            "sportsbook" to "የስፖርት ውርርድ",
            "my_slips" to "የእኔ ቲኬቶች",
            "secure_bank" to "አስተማማኝ ባንክ",
            "admin_panel" to "የአስተዳዳሪ ፓነል",
            "support" to "እርዳታ",
            "balance" to "ቀሪ ሂሳብ",
            "deposit" to "ገንዘብ አስገባ",
            "active_bets" to "ንቁ ቲኬቶች",
            "ssl_encrypted" to "የተጠበቀ ግንኙነት (SSL)",
            "today_matches" to "የዛሬ የቀጥታ ጨዋታዎች",
            "all_sports" to "ሁሉም ስፖርቶች",
            "football" to "እግር ኳስ",
            "basketball" to "ቅርጫት ኳስ",
            "tennis" to "ቴኒስ",
            "place_single_bet" to "ውርርድ ፈጽም",
            "enter_stake" to "የመወራረጃ መጠን (ETB)",
            "potential_return" to "ሊያሸንፉ የሚችሉት",
            "safety_score" to "የአይአይ (AI) የደህንነት ውጤት",
            "prediction_title" to "የአይአይ (AI) ግምታዊ ትንተና",
            "risk_warning" to "ኃላፊነት የሚሰማው ጨዋታ ማስጠንቀቂያ",
            "support_chat" to "የቀጥታ የደንበኞች እርዳታ ማዕከል",
            "chat_placeholder" to "ጥያቄዎን እዚህ ይጻፉ (በአማርኛ፣ በትግርኛ፣ በኦሮምኛ)...",
            "admin_control" to "የShebaOdds የአስተዳዳሪ መቆጣጠሪያ",
            "user_database" to "የሃርድዌር ኦዲት የመረጃ ቋት",
            "quick_stats" to "የአጠቃላይ ሂሳብ ትንተና",
            "total_odds_line" to "ጠቅላላ ኦድስ መስመር",
            "gross_estimation" to "ሊገኝ የሚችል ጠቅላላ ክፍያ",
            "combined_odds" to "የተደመረ ጠቅላላ ኦድስ",
            "total_risk_stake" to "ጠቅላላ የተወራረደበት ገንዘብ",
            "gross_returns" to "ሊመለስ የሚችል ከፍተኛ ክፍያ",
            "multi_bet_slip" to "የተከማቸ ብዙ ጨዋታዎች ቲኬት (Multi-Bet)",
            "clear_all" to "ሁሉንም አጽዳ",
            "ethiopian_calendar" to "የኢትዮጵያ ዘመን አቆጣጠር",
            "select_language" to "ቋንቋ ይምረጡ",
            "app_name" to "ሼባኦድስ",
            "app_tagline" to "ስማርት ቤትስ። ሪል ዊንስ።",
            "app_welcome" to "እንኳን ደህና መጣህ",
            "app_loading" to "በመጫን ላይ...",
            "nav_home" to "መነሻ",
            "nav_football" to "እግር ኳስ",
            "nav_live" to "ቀጥታ ውርርድ",
            "nav_casino" to "ካዚኖ",
            "nav_promotions" to "ማስተዋወቂያዎች",
            "nav_profile" to "መገለጫ",
            "nav_wallet" to "ቦርሳ",
            "nav_history" to "ታሪክ",
            "nav_tax" to "የግብር ማዕከል",
            "nav_support" to "ድጋፍ",
            "nav_settings" to "ቅንብሮች",
            "auth_login" to "ግባ",
            "auth_register" to "ተመዝገብ",
            "auth_email" to "ኢሜይል",
            "auth_password" to "የይለፍ ቃል",
            "auth_confirm_password" to "የይለፍ ቃል አረጋግጥ",
            "auth_username" to "የተጠቃሚ ስም",
            "auth_phone" to "ስልክ ቁጥር",
            "auth_fullname" to "ሙሉ ስም",
            "auth_forgot_password" to "የይለፍ ቃል ረሳሁ",
            "auth_reset_password" to "የይለፍ ቃል ዳግም አስጀምር",
            "auth_remember_me" to "አስታውሰኝ",
            "auth_login_biometric" to "በባዮሜትሪክ ግባ",
            "auth_use_face_id" to "ፌስ አይዲ ተጠቀም",
            "auth_use_fingerprint" to "የጣት አሻራ ተጠቀም",
            "auth_pwd_requirements" to "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች፣ አንድ ትልቅ ፊደል፣ አንድ ትንሽ ፊደል፣ አንድ ቁጥር እና አንድ ልዩ ቁምፊ መያዝ አለበት",
            "wallet_balance" to "ቀሪ ሂሳብ",
            "wallet_bonus_balance" to "ቦነስ ቀሪ ሂሳብ",
            "wallet_deposit" to "ተቀማጭ",
            "wallet_withdraw" to "ማውጫ",
            "wallet_transactions" to "ግብይቶች",
            "wallet_deposit_success" to "ተቀማጭ ስኬታማ!",
            "wallet_withdraw_success" to "ማውጫ ስኬታማ!",
            "bets_place_bet" to "ውርርድ አስቀምጥ",
            "bets_home_win" to "የቤት ድል",
            "bets_away_win" to "የጎብኝ ድል",
            "bets_draw" to "አቻ",
            "bets_over" to "ከላይ",
            "bets_under" to "ከበታች",
            "bets_potential_win" to "ሊገኝ የሚችል ድል",
            "bets_stake" to "ውርርድ",
            "bets_odds" to "ዕድሎች",
            "bets_accumulator" to "አክሙሌተር",
            "bets_cashout" to "ገንዘብ አውጣ",
            "bets_cashout_value" to "ማውጫ ዋጋ",
            "bets_placed" to "ውርርድ ተቀምጧል!",
            "tax_title" to "የግብር ማዕከል",
            "tax_rate" to "የግብር መጠን",
            "tax_rate_value" to "15%",
            "tax_free_limit" to "ከግብር ነጻ ገደብ",
            "tax_free_limit_value" to "100 ብር",
            "tax_total_paid" to "የተከፈለ ጠቅላላ ግብር",
            "tax_total_winnings" to "ግብር የተከፈለበት ጠቅላላ ድል",
            "tax_certificate" to "የግብር የምስክር ወረቀት",
            "tax_monthly_report" to "ወርሃዊ ሪፖርት",
            "matches_live" to "ቀጥታ",
            "matches_upcoming" to "ቀጣይ",
            "matches_finished" to "የተጠናቀቀ",
            "matches_halftime" to "የግማሽ ጊዜ",
            "matches_fulltime" to "ሙሉ ጊዜ",
            "matches_minute" to "ደቂቃ",
            "matches_league" to "ሊግ",
            "matches_stats" to "ስታቲስቲክስ",
            "matches_events" to "ክስተቶች",
            "time_today" to "ዛሬ",
            "time_tomorrow" to "ነገ",
            "time_yesterday" to "ትላንት",
            "time_now" to "አሁን",
            "time_minutes_ago" to "ደቂቃ በፊት",
            "time_hours_ago" to "ሰዓት በፊት",
            "time_days_ago" to "ቀን በፊት",
            "time_am" to "ጥዋት",
            "time_pm" to "ማታ",
            "err_required" to "ይህ መስክ ያስፈልጋል",
            "err_invalid_email" to "እባክዎ ትክክለኛ ኢሜይል ያስገቡ",
            "err_pwd_too_short" to "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት",
            "err_pwd_no_upper" to "የይለፍ ቃል ቢያንስ አንድ ትልቅ ፊደል መያዝ አለበት",
            "err_pwd_no_lower" to "የይለፍ ቃል ቢያንስ አንድ ትንሽ ፊደል መያዝ አለበት",
            "err_pwd_no_num" to "የይለፍ ቃል ቢያንስ አንድ ቁጥር መያዝ አለበት",
            "err_pwd_no_special" to "የይለፍ ቃል ቢያንስ አንድ ልዩ ቁምፊ መያዝ አለበት",
            "err_pwd_no_match" to "የይለፍ ቃሎች አይዛመዱም",
            "err_insufficient_bal" to "በቂ ቀሪ ሂሳብ የለም",
            "err_invalid_amount" to "ዋጋ ትክክል አይደለም",
            "err_network" to "የአውታረ መረብ ስህተት",
            "btn_submit" to "አስገባ",
            "btn_cancel" to "ሰርዝ",
            "btn_confirm" to "አረጋግጥ",
            "btn_back" to "ተመለስ",
            "btn_next" to "ቀጥል",
            "btn_save" to "አስቀምጥ",
            "btn_edit" to "አርትዕ",
            "btn_delete" to "ሰርዝ",
            "btn_close" to "ዝጋ"
        ),
        "ti" to mapOf(
            "sportsbook" to "ናይ ስፖርት ውርርድ",
            "my_slips" to "ናተይ ቲኬታት",
            "secure_bank" to "ውሑስ ባንኪ",
            "admin_panel" to "ናይ ምሕደራ ፓነል",
            "support" to "ሓገዝ",
            "balance" to "ተረፍ ሕሳብ",
            "deposit" to "ገንዘብ የእቱ",
            "active_bets" to "ንቁ ቲኬታት",
            "ssl_encrypted" to "ዝተሓለወ ርክብ (SSL)",
            "today_matches" to "ናይ ሎሚ የቀጥታ ጸወታታት",
            "all_sports" to "ኩሎም ስፖርታት",
            "football" to "ኩዕሶ እግሪ",
            "basketball" to "ኩዕሶ ሰኪዔ",
            "tennis" to "ቴኒስ",
            "place_single_bet" to "ውርርድ ግበሩ",
            "enter_stake" to "መጠን ውርርድ (ETB)",
            "potential_return" to "ክትስዕርዎ እትኽእሉ",
            "safety_score" to "ናይ AI ውሕስነት ነጥቢ",
            "prediction_title" to "ናይ AI ግምታዊ ትንተና",
            "risk_warning" to "ሓላፊነት ዝተሰመዖ ጸወታ መጠንቀቕታ",
            "support_chat" to "ናይ ቀጥታ ሓገዝ ዓማዊል ማእከል",
            "chat_placeholder" to "ሕቶኹም ኣብዚ ጽሓፉ...",
            "admin_control" to "ናይ ShebaOdds ምሕደራ መቖጻጸሪ",
            "user_database" to "ናይ ሃርድዌር ኦዲት መረዳእታ",
            "quick_stats" to "ሓፈሻዊ ናይ ሕሳብ ትንተና",
            "total_odds_line" to "ጠቕላላ ኦድስ መስመር",
            "gross_estimation" to "ክረክብ ዝኽእል ጠቕላላ ክፍሊት",
            "combined_odds" to "ዝተደመረ ጠቕላላ ኦድስ",
            "total_risk_stake" to "ጠቕላላ ዝተወራረደ ገንዘብ",
            "gross_returns" to "ክምለስ ዝኽእል ዝለዓለ ክፍሊት",
            "multi_bet_slip" to "ዝተዋህለለ ብዙሕ ጸወታታት ቲኬት",
            "clear_all" to "ኩሉ ኣጽሪ",
            "ethiopian_calendar" to "ናይ ኢትዮጵያ ዘመን ኣቆጻጽራ",
            "select_language" to "ቋንቋ ምረጹ"
        ),
        "om" to mapOf(
            "sportsbook" to "Wirdii Ispoortii",
            "my_slips" to "Koo Kaardii",
            "secure_bank" to "Baanki Amansiisaa",
            "admin_panel" to "Gubbaa Admin",
            "support" to "Deeggarsa",
            "balance" to "Hanga Maallaqaa",
            "deposit" to "Maallaqa Galchi",
            "active_bets" to "Kaardii Banamaa",
            "ssl_encrypted" to "Cufama SSL Eegame",
            "today_matches" to "Taphoota Live Har'aa",
            "all_sports" to "Ispoortii Hundumaa",
            "football" to "Kubbaa Miilaa",
            "basketball" to "Kubbaa Saaphanaa",
            "tennis" to "Tenisii",
            "place_single_bet" to "Wirdii Gadi Lakkisi",
            "enter_stake" to "Hanga Kafaltii (ETB)",
            "potential_return" to "Argannoo Tilmaamamaa",
            "safety_score" to "Qabxii Nageenya AI",
            "prediction_title" to "Xiinxala Raaga AI",
            "risk_warning" to "AKEEKKACHIISA TAPHA ITTI GAAFATAMUMMAA",
            "support_chat" to "Giddugala Deeggarsa Kallattii",
            "chat_placeholder" to "Gaaffii keessan asitti barreessaa...",
            "admin_control" to "To'annoo Admin ShebaOdds",
            "user_database" to "Kuusaa Ragaa Hardware",
            "quick_stats" to "Istaatistiksii Waliigalaa",
            "total_odds_line" to "Hanga Odds Hundumaa",
            "gross_estimation" to "Kafaltii Tilmaamamaa",
            "combined_odds" to "Walitti Dhufeenya Odds",
            "total_risk_stake" to "Wirdii Guutuu Qabame",
            "gross_returns" to "Argannoo Ol'aanaa Tilmaamamaa",
            "multi_bet_slip" to "Tikkee Wirdii Baay'ee",
            "clear_all" to "Hundumaa Haqi",
            "ethiopian_calendar" to "Dhaha Itoophiyaa",
            "select_language" to "Afaan Filadhu"
        )
    )

    fun get(key: String, lang: String): String {
        val langMap = translations[lang] ?: translations["en"]!!
        return langMap[key] ?: translations["en"]!![key] ?: key
    }
}
